---
- Network:
  - Unifi:
      href: https://unifi.home
      description: Unifi Controller
      ping: 10.1.1.1
      siteMonitor: https://unifi.home
  - Hasivo:
      href: http://10.1.1.104/
      description: Core switch
      ping: 10.1.1.104
      siteMonitor: http://10.1.1.104
- Services:
  - Home Assistant:
      href: https://hass.esrever.uno
      description: Home automation
      ping: trip
      siteMonitor: https://hass.esrever.uno
  - Grafana:
      href: https://grafana.esrever.uno
      description: Home automation
      ping: trip
      siteMonitor: https://grafana.esrever.uno
  - Tandoor:
      href: https://tandoor.esrever.uno
      description: Recipe aggregator
      siteMonitor: https://tandoor.esrever.uno
  - AptCacherNg:
      href: https://aptcache.esrever.uno/acng-report.html
      description: Apt cache
      siteMonitor: https://aptcache.esrever.uno/acng-report.html
- Misc:
    - Uptime Robot:
        href: https://uptimerobot.com/
        description: Uptime monitoring
        siteMonitor: https://uptimerobot.com/
        widget:
            type: uptimerobot
            url: https://api.uptimerobot.com
            key: "{{HOMEPAGE_FILE_UPTIMEROBOT_API_KEY}}"
