name: "Cachix"
on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CACHE_NAME: ${{ github.actor }}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: ${{ env.CACHE_NAME }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - name: Cache
      run: |
        nix flake archive --json \
          | jq -r '.path,(.inputs|to_entries[].value.path)' \
          | cachix push "$CACHE_NAME"
